.TH *xc_fopen 3

.SH LIBRARY
\" Indicate #includes, library name, -L and -l flags
.nf
.na
#include <xtendc.h>
-lxtendc
.ad
.fi

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na
FILE    *xc_fopen(const char *filename, const char *mode)
.ad
.fi

.SH ARGUMENTS
.nf
.na
filename:   Name of the file to be opened
mode:       "r" or "w", passed to fopen() or popen()
.ad
.fi

.SH RETURN VALUES

A pointer to the FILE structure or NULL if open failed

.SH DESCRIPTION

Open a raw data file using fopen() or a gzipped, bzipped, or
xzipped file using popen().  Must be used in conjunction with
xc_fclose() to ensure that fclose() or pclose() is called where
appropriate.

.SH SEE ALSO

fopen(3), popen(3), gzip(1), bzip2(1), xz(1)

