.TH num_size 3

.SH LIBRARY
\" Indicate #includes, library name, -L and -l flags
.nf
.na
#include <xtend.h>
-lxtend
.ad
.fi

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na
int     num_size(long val, unsigned base)
.ad
.fi

.SH ARGUMENTS
.nf
.na
val:    The number for which digits are to be counted
base:   The number base, between 2 and 36
.ad
.fi

.SH RETURN VALUES

The number of base "base" digits in val, or -1 if base is invalid

.SH DESCRIPTION

num_size() computes the number of digits in val, assuming the
given base.
