.TH strptrcmp 3

.SH LIBRARY
\" Indicate #includes, library name, -L and -l flags
.nf
.na
#include <xtendc.h>
-lxtendc
.ad
.fi

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na
int     strptrcmp(const char **p1, const char **p2)
.ad
.fi

.SH ARGUMENTS
.nf
.na
p1, p2: Pointers to pointers to the strings to compare
.ad
.fi

.SH RETURN VALUES

0 if the strings are the same, a value < 0 if the string at p1
is lexically < that at p2, a value > 0 otherwise.

.SH DESCRIPTION

Compare two strings via indirect pointers.  This can be used by
qsort(), heapsort(), etc. to sort an argv-style pointer array,
swapping only the pointers rather than the string contents.

.SH SEE ALSO

strcmp(3)

