.TH xc_fclose 3

.SH LIBRARY
\" Indicate #includes, library name, -L and -l flags
.nf
.na
#include <xtendc.h>
-lxtendc
.ad
.fi

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na
int     xc_fclose(FILE *stream)
.ad
.fi

.SH ARGUMENTS
.nf
.na
stream: The FILE structure to be closed
.ad
.fi

.SH RETURN VALUES

The value returned by fclose() or pclose()

.SH DESCRIPTION

Close a FILE stream with fclose() or pclose() as appropriate.
Automatically determines the proper close function to call using
S_ISFIFO on the stream stat structure.

.SH SEE ALSO

fopen(3), popen(3), gzip(1), bzip2(1), xz(1)

