.TH xt_ff_t
.SH NAME    \" Section header
.PP

xt_ff_t - Fast file stream class library

.SH "DESCRIPTION"

The
.B xt_ff_t
data type is an opaque structure implementing stream I/O comparable
to the traditional "FILE *" standard I/O functions, but simpler and
much faster.  CPU time ranges from a small fraction of that used by
FILE functions to about half.

.SH FUNCTIONS
.nf
.na
xt_ff_close(3) - Close a stream opened by xt_ff_open(3)
xt_ff_close_raw(3) - Close a stream opened by xt_ff_open_raw(3)
xt_ff_dopen(3) - Create a stream connected to an existing file descriptor
xt_ff_getc(3) - Read one character from a stream
xt_ff_gets(3) - Read one line from a stream
xt_ff_open(3) - Create a new stream connected to a raw or compressed file
xt_ff_open_raw(3) - Create a new stream connected to a raw file
xt_ff_pclose(3) - Close a stream created by xt_ff_popen(3)
xt_ff_popen(3) - Create a stream connected to a process
xt_ff_printf(3) - Print formatted data to a stream
xt_ff_putc(3) - Print a single character to a stream
xt_ff_puts(3) - Print a character string to a stream
xt_ff_read(3) - Read a fixed number of bytes from a stream
xt_ff_read_line_malloc(3) - Read a line and allocate memory for it
xt_ff_rewind(3) - Reset file descriptor of a stream to the beginning of file
xt_ff_seeko(3) - Set file descriptor of a stream to any position
xt_ff_stdin(3) - Create a stream connected to file descriptor 0
xt_ff_stdout(3) - Create a stream connected to file descriptor 1
xt_ff_tmpfile(3) - Create a stream connected to a new temporary file
xt_ff_ungetc(3) - Put back a character read by xt_ff_getc(3)
.ad
.fi

.SH "SEE ALSO"
stdio(3)

.SH AUTHOR
.nf
.na
J. Bacon
