/***************************************************************************
 *  This file is automatically generated by gen-get-set.  Be sure to keep
 *  track of any manual changes.
 *
 *  These generated functions are not expected to be perfect.  Check and
 *  edit as needed before adding to your code.
 ***************************************************************************/

#include <string.h>
#include <ctype.h>
#include <stdbool.h>        // In case of bool
#include <stdint.h>         // In case of int64_t, etc
#include "string.h"         // strlcpy() on Linux
#include "dsv-private.h"


/***************************************************************************
 *  Library:
 *      #include <xtend/dsv.h>
 *      -lxtend
 *
 *  Description:
 *      Accessor for array_size member in a dsv_line_t structure.
 *      Use this function to get array_size in a dsv_line_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      dsv_line_ptr    Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member array_size.
 *
 *  Examples:
 *      dsv_line_t      dsv_line;
 *      size_t          array_size;
 *
 *      array_size = dsv_line_get_array_size(&dsv_line);
 *
 *  History: 
 *  Date        Name        Modification
 *  2023-05-27  gen-get-set Auto-generated from dsv-private.h
 ***************************************************************************/

size_t    dsv_line_get_num_fields_array_size(dsv_line_t *dsv_line_ptr)

{
    return dsv_line_ptr->num_fields_array_size;
}


/***************************************************************************
 *  Library:
 *      #include <xtend/dsv.h>
 *      -lxtend
 *
 *  Description:
 *      Accessor for num_fields member in a dsv_line_t structure.
 *      Use this function to get num_fields in a dsv_line_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      dsv_line_ptr    Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member num_fields.
 *
 *  Examples:
 *      dsv_line_t      dsv_line;
 *      size_t          num_fields;
 *
 *      num_fields = dsv_line_get_num_fields(&dsv_line);
 *
 *  History: 
 *  Date        Name        Modification
 *  2023-05-27  gen-get-set Auto-generated from dsv-private.h
 ***************************************************************************/

size_t    dsv_line_get_num_fields(dsv_line_t *dsv_line_ptr)

{
    return dsv_line_ptr->num_fields;
}


/***************************************************************************
 *  Library:
 *      #include <xtend/dsv.h>
 *      -lxtend
 *
 *  Description:
 *      Accessor for fields member in a dsv_line_t structure.
 *      Use this function to get fields in a dsv_line_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      dsv_line_ptr    Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member fields.
 *
 *  Examples:
 *      dsv_line_t      dsv_line;
 *      char **         fields;
 *
 *      fields = dsv_line_get_fields(&dsv_line);
 *
 *  History: 
 *  Date        Name        Modification
 *  2023-05-27  gen-get-set Auto-generated from dsv-private.h
 ***************************************************************************/

char **    dsv_line_get_fields(dsv_line_t *dsv_line_ptr)

{
    return dsv_line_ptr->fields;
}


/***************************************************************************
 *  Library:
 *      #include <xtend/dsv.h>
 *      -lxtend
 *
 *  Description:
 *      Accessor for an array element of fields member in a dsv_line_t
 *      structure. Use this function to get dsv_line_ptr->fields[c]
 *      in a dsv_line_t object from non-member functions.
 *
 *  Arguments:
 *      dsv_line_ptr    Pointer to the structure to get
 *      c               Subscript to the fields array
 *
 *  Returns:
 *      Value of one element of structure member fields.
 *
 *  Examples:
 *      dsv_line_t      dsv_line;
 *      size_t          c;
 *      char **         fields_element;
 *
 *      fields_element = dsv_line_get_fields_ae(&dsv_line, c);
 *
 *  History: 
 *  Date        Name        Modification
 *  2023-05-27  gen-get-set Auto-generated from dsv-private.h
 ***************************************************************************/

char * dsv_line_get_fields_ae(dsv_line_t *dsv_line_ptr, size_t c)

{
    return dsv_line_ptr->fields[c];
}


/***************************************************************************
 *  Library:
 *      #include <xtend/dsv.h>
 *      -lxtend
 *
 *  Description:
 *      Accessor for delims member in a dsv_line_t structure.
 *      Use this function to get delims in a dsv_line_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      dsv_line_ptr    Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member delims.
 *
 *  Examples:
 *      dsv_line_t      dsv_line;
 *      char *          delims;
 *
 *      delims = dsv_line_get_delims(&dsv_line);
 *
 *  History: 
 *  Date        Name        Modification
 *  2023-05-27  gen-get-set Auto-generated from dsv-private.h
 ***************************************************************************/

char *    dsv_line_get_delims(dsv_line_t *dsv_line_ptr)

{
    return dsv_line_ptr->delims;
}


/***************************************************************************
 *  Library:
 *      #include <xtend/dsv.h>
 *      -lxtend
 *
 *  Description:
 *      Accessor for an array element of delims member in a dsv_line_t
 *      structure. Use this function to get dsv_line_ptr->delims[c]
 *      in a dsv_line_t object from non-member functions.
 *
 *  Arguments:
 *      dsv_line_ptr    Pointer to the structure to get
 *      c               Subscript to the delims array
 *
 *  Returns:
 *      Value of one element of structure member delims.
 *
 *  Examples:
 *      dsv_line_t      dsv_line;
 *      size_t          c;
 *      char *          delims_element;
 *
 *      delims_element = dsv_line_get_delims_ae(&dsv_line, c);
 *
 *  History: 
 *  Date        Name        Modification
 *  2023-05-27  gen-get-set Auto-generated from dsv-private.h
 ***************************************************************************/

char  dsv_line_get_delims_ae(dsv_line_t *dsv_line_ptr, size_t c)

{
    return dsv_line_ptr->delims[c];
}
