    
/*
 *  Generated by /home/bacon/auto-gen-get-set-opaque
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the xt_dsv_line_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

/* temp-dsv-accessors.c */
size_t xt_dsv_line_get_array_size(xt_dsv_line_t *xt_dsv_line_ptr);
size_t xt_dsv_line_get_num_fields(xt_dsv_line_t *xt_dsv_line_ptr);
char **xt_dsv_line_get_fields(xt_dsv_line_t *xt_dsv_line_ptr);
char *xt_dsv_line_get_fields_ae(xt_dsv_line_t *xt_dsv_line_ptr, size_t c);
char *xt_dsv_line_get_delims(xt_dsv_line_t *xt_dsv_line_ptr);
char xt_dsv_line_get_delims_ae(xt_dsv_line_t *xt_dsv_line_ptr, size_t c);
