/***************************************************************************
 *  This file is automatically generated by gen-get-set.  Be sure to keep
 *  track of any manual changes.
 *
 *  These generated functions are not expected to be perfect.  Check and
 *  edit as needed before adding to your code.
 ***************************************************************************/

#include <string.h>
#include <ctype.h>
#include <stdbool.h>        // In case of bool
#include <stdint.h>         // In case of int64_t, etc
#include "string.h"         // strlcpy() on Linux
#include "dsv-private.h"


/***************************************************************************
 *  Library:
 *      #include <xtend/dsv.h>
 *      -lxtend
 *
 *  Description:
 *      Accessor for array_size member in a xt_dsv_line_t structure.
 *      Use this function to get array_size in a xt_dsv_line_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      xt_dsv_line_ptr    Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member array_size.
 *
 *  Examples:
 *      xt_dsv_line_t      xt_dsv_line;
 *      size_t          array_size;
 *
 *      array_size = xt_dsv_line_get_array_size(&xt_dsv_line);
 *
 *  History: 
 *  Date        Name        Modification
 *  2023-05-27  gen-get-set Auto-generated from dsv-private.h
 ***************************************************************************/

size_t    xt_dsv_line_get_num_fields_array_size(xt_dsv_line_t *xt_dsv_line_ptr)

{
    return xt_dsv_line_ptr->num_fields_array_size;
}


/***************************************************************************
 *  Library:
 *      #include <xtend/dsv.h>
 *      -lxtend
 *
 *  Description:
 *      Accessor for num_fields member in a xt_dsv_line_t structure.
 *      Use this function to get num_fields in a xt_dsv_line_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      xt_dsv_line_ptr    Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member num_fields.
 *
 *  Examples:
 *      xt_dsv_line_t      xt_dsv_line;
 *      size_t          num_fields;
 *
 *      num_fields = xt_dsv_line_get_num_fields(&xt_dsv_line);
 *
 *  History: 
 *  Date        Name        Modification
 *  2023-05-27  gen-get-set Auto-generated from dsv-private.h
 ***************************************************************************/

size_t    xt_dsv_line_get_num_fields(xt_dsv_line_t *xt_dsv_line_ptr)

{
    return xt_dsv_line_ptr->num_fields;
}


/***************************************************************************
 *  Library:
 *      #include <xtend/dsv.h>
 *      -lxtend
 *
 *  Description:
 *      Accessor for fields member in a xt_dsv_line_t structure.
 *      Use this function to get fields in a xt_dsv_line_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      xt_dsv_line_ptr    Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member fields.
 *
 *  Examples:
 *      xt_dsv_line_t      xt_dsv_line;
 *      char **         fields;
 *
 *      fields = xt_dsv_line_get_fields(&xt_dsv_line);
 *
 *  History: 
 *  Date        Name        Modification
 *  2023-05-27  gen-get-set Auto-generated from dsv-private.h
 ***************************************************************************/

char **    xt_dsv_line_get_fields(xt_dsv_line_t *xt_dsv_line_ptr)

{
    return xt_dsv_line_ptr->fields;
}


/***************************************************************************
 *  Library:
 *      #include <xtend/dsv.h>
 *      -lxtend
 *
 *  Description:
 *      Accessor for an array element of fields member in a xt_dsv_line_t
 *      structure. Use this function to get xt_dsv_line_ptr->fields[c]
 *      in a xt_dsv_line_t object from non-member functions.
 *
 *  Arguments:
 *      xt_dsv_line_ptr    Pointer to the structure to get
 *      c               Subscript to the fields array
 *
 *  Returns:
 *      Value of one element of structure member fields.
 *
 *  Examples:
 *      xt_dsv_line_t      xt_dsv_line;
 *      size_t          c;
 *      char **         fields_element;
 *
 *      fields_element = xt_dsv_line_get_fields_ae(&xt_dsv_line, c);
 *
 *  History: 
 *  Date        Name        Modification
 *  2023-05-27  gen-get-set Auto-generated from dsv-private.h
 ***************************************************************************/

char * xt_dsv_line_get_fields_ae(xt_dsv_line_t *xt_dsv_line_ptr, size_t c)

{
    return xt_dsv_line_ptr->fields[c];
}


/***************************************************************************
 *  Library:
 *      #include <xtend/dsv.h>
 *      -lxtend
 *
 *  Description:
 *      Accessor for delims member in a xt_dsv_line_t structure.
 *      Use this function to get delims in a xt_dsv_line_t object
 *      from non-member functions.
 *
 *  Arguments:
 *      xt_dsv_line_ptr    Pointer to the structure to set
 *
 *  Returns:
 *      Value of the structure member delims.
 *
 *  Examples:
 *      xt_dsv_line_t      xt_dsv_line;
 *      char *          delims;
 *
 *      delims = xt_dsv_line_get_delims(&xt_dsv_line);
 *
 *  History: 
 *  Date        Name        Modification
 *  2023-05-27  gen-get-set Auto-generated from dsv-private.h
 ***************************************************************************/

char *    xt_dsv_line_get_delims(xt_dsv_line_t *xt_dsv_line_ptr)

{
    return xt_dsv_line_ptr->delims;
}


/***************************************************************************
 *  Library:
 *      #include <xtend/dsv.h>
 *      -lxtend
 *
 *  Description:
 *      Accessor for an array element of delims member in a xt_dsv_line_t
 *      structure. Use this function to get xt_dsv_line_ptr->delims[c]
 *      in a xt_dsv_line_t object from non-member functions.
 *
 *  Arguments:
 *      xt_dsv_line_ptr    Pointer to the structure to get
 *      c               Subscript to the delims array
 *
 *  Returns:
 *      Value of one element of structure member delims.
 *
 *  Examples:
 *      xt_dsv_line_t      xt_dsv_line;
 *      size_t          c;
 *      char *          delims_element;
 *
 *      delims_element = xt_dsv_line_get_delims_ae(&xt_dsv_line, c);
 *
 *  History: 
 *  Date        Name        Modification
 *  2023-05-27  gen-get-set Auto-generated from dsv-private.h
 ***************************************************************************/

char  xt_dsv_line_get_delims_ae(xt_dsv_line_t *xt_dsv_line_ptr, size_t c)

{
    return xt_dsv_line_ptr->delims[c];
}
