    
/*
 *  Generated by /home/bacon/auto-gen-get-set-opaque
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the dsv_line_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

/* temp-dsv-accessors.c */
size_t dsv_line_get_array_size(dsv_line_t *dsv_line_ptr);
size_t dsv_line_get_num_fields(dsv_line_t *dsv_line_ptr);
char **dsv_line_get_fields(dsv_line_t *dsv_line_ptr);
char *dsv_line_get_fields_ae(dsv_line_t *dsv_line_ptr, size_t c);
char *dsv_line_get_delims(dsv_line_t *dsv_line_ptr);
char dsv_line_get_delims_ae(dsv_line_t *dsv_line_ptr, size_t c);
