    
/*
 *  Generated by /usr/local/bin/auto-gen-get-set-opaque
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the xt_ff_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

/* temp-fast-file-accessors.c */
unsigned char *xt_ffile_get_buff(xt_ff_t *xt_ffile_ptr);
unsigned char xt_ffile_get_buff_ae(xt_ff_t *xt_ffile_ptr, size_t c);
unsigned char *xt_ffile_get_start_ptr(xt_ff_t *xt_ffile_ptr);
unsigned char xt_ffile_get_start_ptr_ae(xt_ff_t *xt_ffile_ptr, size_t c);
ssize_t xt_ffile_get_bytes_read(xt_ff_t *xt_ffile_ptr);
ssize_t xt_ffile_get_buff_index(xt_ff_t *xt_ffile_ptr);
ssize_t xt_ffile_get_disk_block_size(xt_ff_t *xt_ffile_ptr);
ssize_t xt_ffile_get_buff_size(xt_ff_t *xt_ffile_ptr);
int xt_ffile_get_fd(xt_ff_t *xt_ffile_ptr);
int xt_ffile_get_flags(xt_ff_t *xt_ffile_ptr);
pid_t xt_ffile_get_child_pid(xt_ff_t *xt_ffile_ptr);
