
/*
 *  Generated by /usr/local/bin/auto-gen-get-set-opaque
 *
 *  Mutator functions for setting with no sanity checking.  Use these to
 *  set structure members from functions outside the xt_ff_t
 *  class.  These macros perform no data validation.  Hence, they achieve
 *  maximum performance where data are guaranteed correct by other means.
 *  Use the mutator functions (same name as the macro, but lower case)
 *  for more robust code with a small performance penalty.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

/* temp-fast-file-mutators.c */
int xt_ffile_set_buff(xt_ff_t *xt_ffile_ptr, unsigned char *new_buff);
int xt_ffile_set_buff_ae(xt_ff_t *xt_ffile_ptr, size_t c, unsigned char new_buff_element);
int xt_ffile_set_buff_cpy(xt_ff_t *xt_ffile_ptr, unsigned char *new_buff, size_t array_size);
int xt_ffile_set_start_ptr(xt_ff_t *xt_ffile_ptr, unsigned char *new_start_ptr);
int xt_ffile_set_start_ptr_ae(xt_ff_t *xt_ffile_ptr, size_t c, unsigned char new_start_ptr_element);
int xt_ffile_set_start_ptr_cpy(xt_ff_t *xt_ffile_ptr, unsigned char *new_start_ptr, size_t array_size);
int xt_ffile_set_bytes_read(xt_ff_t *xt_ffile_ptr, ssize_t new_bytes_read);
int xt_ffile_set_buff_index(xt_ff_t *xt_ffile_ptr, ssize_t new_buff_index);
int xt_ffile_set_disk_block_size(xt_ff_t *xt_ffile_ptr, ssize_t new_disk_block_size);
int xt_ffile_set_buff_size(xt_ff_t *xt_ffile_ptr, ssize_t new_buff_size);
int xt_ffile_set_fd(xt_ff_t *xt_ffile_ptr, int new_fd);
int xt_ffile_set_flags(xt_ff_t *xt_ffile_ptr, int new_flags);
int xt_ffile_set_child_pid(xt_ff_t *xt_ffile_ptr, pid_t new_child_pid);
